- name: add SBT repo
  apt_repository: repo='deb https://dl.bintray.com/sbt/debian /' state=present

- name: add docker repo key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=642AC823 state=present

- name: install sbt
  apt: update_cache=yes pkg=sbt state=present
